blueprint:
  name: Light With Motion & Switch Control
  description: Turn a light on based on detected motion or via normal smart switch
  domain: automation
  input:
    light_switch:
      name: Light Switch
      description: This switch will switch the light
      selector:
        entity:
          domain: switch
    target_light:
      name: Lights
      description: The lights to keep in sync.
      selector:
        target:
          entity:
            domain: light

trigger:
  platform: state
  entity_id: !input light_switch
action:
  service: >
    {% if trigger.to_state.state == "on" %}
      light.turn_on
    {% else %}
      light.turn_off
    {% endif %}
  target: !input target_light
